// lib/agents.js

export const agents = [
  {
    id: 'agent-1',
    name: 'Alex Morgan',
    email: 'alex@estateflow.co',
    phone: '+27 71 001 0001',
    role: 'Senior Agent',
    location: 'Cape Town, Western Cape',
    status: 'Active',
    avatar: null,
    joinDate: '2023-01-15',
    salesThisMonth: 3,
    totalListings: 12,
  },
  {
    id: 'agent-2',
    name: 'Thabo Nkosi',
    email: 'thabo@estateflow.co',
    phone: '+27 82 002 0002',
    role: 'Buyer Specialist',
    location: 'Durban, KwaZulu-Natal',
    status: 'Active',
    avatar: null,
    joinDate: '2023-03-22',
    salesThisMonth: 2,
    totalListings: 8,
  },
  {
    id: 'agent-3',
    name: 'Lerato van Niekerk',
    email: 'lerato@estateflow.co',
    phone: '+27 76 003 0003',
    role: 'Luxury Properties',
    location: 'Sandton, Gauteng',
    status: 'Active',
    avatar: null,
    joinDate: '2022-11-05',
    salesThisMonth: 4,
    totalListings: 15,
  },
  {
    id: 'agent-4',
    name: 'Sipho Dlamini',
    email: 'sipho@estateflow.co',
    phone: '+27 83 004 0004',
    role: 'Investment Advisor',
    location: 'Midrand, Gauteng',
    status: 'Inactive',
    avatar: null,
    joinDate: '2024-02-10',
    salesThisMonth: 0,
    totalListings: 5,
  },
];