// lib/data.js
export const leads = [
  {
    id: 'lead-1',
    name: 'Thato Moyo',
    email: 'thato.moyo@gmail.com',
    phone: '+27 71 123 4567',
    type: 'buyer',
    stage: 'contacted',
    propertyType: 'apartment',
    budget: '600000-800000',
    location: 'Durban, KwaZulu-Natal',
    source: 'Online Inquiry',
    assignedTo: 'Alex Morgan',
    createdAt: '2025-04-05',
    status: 'active',
    notes: [
      {
        id: 'n1',
        text: 'Interested in beachfront apartments with sea views and secure parking.',
        author: 'Alex',
        date: '2025-04-05',
      },
    ],
    tasks: [
      {
        id: 't1',
        title: 'Send property list',
        due: '2025-04-10',
        completed: false,
      },
    ],
  },
  {
    id: 'lead-2',
    name: 'Jabu Ndlovu',
    email: 'jabu.ndlovu@icloud.com',
    phone: '+27 82 987 6543',
    type: 'seller',
    stage: 'qualified',
    propertyType: 'single-family',
    budget: '1200000',
    location: 'Sandton, Gauteng',
    source: 'Referral',
    assignedTo: 'Alex Morgan',
    createdAt: '2025-04-03',
    status: 'active',
    notes: [
      {
        id: 'n2',
        text: 'Wants quick sale due to relocation. Open to negotiations.',
        author: 'Alex',
        date: '2025-04-04',
      },
    ],
    tasks: [],
  },
  {
    id: 'lead-3',
    name: 'Lerato van Niekerk',
    email: 'lerato.van@gmail.com',
    phone: '+27 76 555 1234',
    type: 'buyer',
    stage: 'new',
    propertyType: 'townhouse',
    budget: '900000-1500000',
    location: 'Cape Town, Western Cape',
    source: 'Open House',
    assignedTo: 'Alex Morgan',
    createdAt: '2025-04-06',
    status: 'active',
    notes: [],
    tasks: [
      {
        id: 't2',
        title: 'Schedule viewing',
        due: '2025-04-08',
        completed: false,
      },
    ],
  },
  {
    id: 'lead-4',
    name: 'Sipho Dlamini',
    email: 'sipho.dlamini@live.com',
    phone: '+27 83 444 9999',
    type: 'investor',
    stage: 'qualified',
    propertyType: 'land',
    budget: '500000-800000',
    location: 'Midrand, Gauteng',
    source: 'Website Form',
    assignedTo: 'Alex Morgan',
    createdAt: '2025-04-02',
    status: 'active',
    notes: [
      {
        id: 'n3',
        text: 'Looking for land to develop townhouse units. Prefers near transport routes.',
        author: 'Alex',
        date: '2025-04-03',
      },
    ],
    tasks: [
      {
        id: 't3',
        title: 'Research zoning laws',
        due: '2025-04-09',
        completed: true,
      },
    ],
  },
  {
    id: 'lead-5',
    name: 'Nomsa Khumalo',
    email: 'nomsa.khumalo@yahoo.com',
    phone: '+27 60 111 2222',
    type: 'buyer',
    stage: 'converted',
    propertyType: 'apartment',
    budget: '750000',
    location: 'Umhlanga, KwaZulu-Natal',
    source: 'Social Media',
    assignedTo: 'Alex Morgan',
    createdAt: '2025-03-28',
    status: 'active',
    notes: [
      {
        id: 'n4',
        text: 'Closed deal on luxury apartment. Will refer friends.',
        author: 'Alex',
        date: '2025-04-01',
      },
    ],
    tasks: [],
  },
];