// lib/properties.js

export const properties = [
  {
    id: 'prop-1',
    title: 'Modern Apartment in Sandton',
    type: 'apartment',
    price: 1850000,
    location: 'Sandton, Gauteng',
    bedrooms: 2,
    bathrooms: 2,
    size: 95, // in m²
    image: 'https://source.unsplash.com/random/800x600/?sandton,apartment',
    status: 'available',
    description: 'Stylish 2-bedroom apartment in the heart of Sandton with secure parking and gym access.',
    leadId: 'lead-1', // Linked to Thato Moyo
  },
  {
    id: 'prop-2',
    title: 'Family Home in Pretoria East',
    type: 'single-family',
    price: 2400000,
    location: 'Pretoria, Gauteng',
    bedrooms: 4,
    bathrooms: 3,
    size: 220,
    image: 'https://source.unsplash.com/random/800x600/?pretoria,house',
    status: 'under-contract',
    description: 'Spacious family home with garden, pool, and double garage in a quiet neighborhood.',
    leadId: 'lead-2', // Linked to Jabu Ndlovu
  },
  {
    id: 'prop-3',
    title: 'Beachfront Unit in Umhlanga',
    type: 'apartment',
    price: 3200000,
    location: 'Umhlanga, KwaZulu-Natal',
    bedrooms: 3,
    bathrooms: 2,
    size: 110,
    image: 'https://source.unsplash.com/random/800x600/?umhlanga,ocean',
    status: 'available',
    description: 'Luxury beachfront unit with ocean views, concierge, and private balcony.',
    leadId: null,
  },
  {
    id: 'prop-4',
    title: 'Townhouse in Ballito',
    type: 'townhouse',
    price: 1650000,
    location: 'Ballito, KwaZulu-Natal',
    bedrooms: 3,
    bathrooms: 2,
    size: 140,
    image: 'https://source.unsplash.com/random/800x600/?ballito,townhouse',
    status: 'available',
    description: 'Secure estate townhouse with modern finishes, ideal for families or investors.',
    leadId: null,
  },
  {
    id: 'prop-5',
    title: 'Luxury Villa in Camps Bay',
    type: 'single-family',
    price: 8500000,
    location: 'Camps Bay, Western Cape',
    bedrooms: 5,
    bathrooms: 4,
    size: 380,
    image: 'https://source.unsplash.com/random/800x600/?campstown,bay,villa',
    status: 'available',
    description: 'Premium villa with infinity pool, sea views, and smart home automation.',
    leadId: null,
  },
  {
    id: 'prop-6',
    title: 'Studio Apartment in Cape Town City Bowl',
    type: 'apartment',
    price: 850000,
    location: 'Cape Town, Western Cape',
    bedrooms: 1,
    bathrooms: 1,
    size: 55,
    image: 'https://source.unsplash.com/random/800x600/?capetown,city,bowl',
    status: 'available',
    description: 'Compact studio in the city center, perfect for young professionals.',
    leadId: 'lead-3', // Linked to Lerato van Niekerk
  },
  {
    id: 'prop-7',
    title: 'Wine Estate Home in Stellenbosch',
    type: 'single-family',
    price: 4200000,
    location: 'Stellenbosch, Western Cape',
    bedrooms: 4,
    bathrooms: 3,
    size: 300,
    image: 'https://source.unsplash.com/random/800x600/?stellenbosch,wine,estate',
    status: 'available',
    description: 'Beautiful home on a working wine estate with mountain views and vineyard access.',
    leadId: null,
  },
];